### PR TITLE
Bump to support Django 5

### PR DESCRIPTION
**Pull request by babus**
Django 5 is released! Checking if the support could be done without making any code changes with the existing series of tests.

### CODE REVIEW

**Comment by mnogokotin** [comment]
please accept )

**Comment by nrbnlulu** [comment]
Tests are failing. It seems that there is no veraion 5.0 on pypi

**Comment by babus** [comment]
Django 5.0 drops support for Python 3.8 and 3.9.

**Comment by babus** [comment]
> Tests are failing. It seems that there is no veraion 5.0 on pypi

I have added the exclusions for Django 5, could you please accept the workflows?

**Comment by nrbnlulu** [comment]
OK cool please add  a  RELEASE.md file and I can merge it

**Comment by nrbnlulu** [comment]
OK cool please add  a  RELEASE.md file and I can merge it

**Comment by nrbnlulu** [comment]
### Release Notes

error
****  
Here is an example format:
```md
Release type: <patch/minor/major>
[//]: # (describe your changes here...)
```

**Comment by babus** [comment]
> OK cool please add a RELEASE.md file and I can merge it

Done, thanks!

**Pull request merged**
